name: 'Terraform Deploy'
description: 'Deploys the Terraform'
inputs:
  environment:
    description: 'Deployment environment'
    required: true
  serviceprinciple_key:
    description: 'Deployment environment'
    required: true
  subscription_id:
    description: 'ID for deployment subscription'
    required: true
    


runs:
  using: 'composite'
  steps:
    - name: Get code
      uses: actions/checkout@v3

    - name: Get dir info
      shell: bash
      run: ls

    - name: cd into tf dir
      shell: bash
      run: cd terraform

    - name: Get dir info again 
      shell: bash
      run: ls

    - name: Setup Terraform
      id: TF-Setup
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Validate
      id: validate
      if: github.ref == 'refs/heads/main'
      shell: bash
      run: |
        ls
        terraform init -backend-config="./backend/${{ inputs.environment }}-backend.hcl"
        terraform validate
      env:
        TF_VAR_serviceprinciple_key: ${{ inputs.serviceprinciple_key }}
        TF_VAR_environment: ${{ inputs.environment }}
        TF_VAR_subscription_id: ${{ inputs.subscription_id }}

    - name: Terraform Plan
      shell: bash
      run: |
        ls
        terraform init -backend-config="./backend/${{ inputs.environment }}-backend.hcl"
        terraform plan -var-file="./terraform/config/common.tfvars" -var-file="./terraform/config/${{ inputs.environment }}.tfvars"
      env:
        TF_VAR_environment: ${{ inputs.environment }}
        TF_VAR_subscription_id: ${{ inputs.subscription_id }}

    #- name: Terraform Apply
    #  shell: bash
    #  if: ${{ github.event.inputs.runApply == 'true' }}
    #  run: |
    #    terraform init -backend-config="./backend/${{ inputs.environment }}-backend.hcl"
    #    terraform apply -var-file="config/common.tfvars" -var-file="config/${{ inputs.environment }}.tfvars" -auto-approve -input=false
    #  env:
    #    TF_VAR_environment: ${{ inputs.environment }}
    #    TF_VAR_subscription_id: ${{ inputs.subscription_id }}
