name: Terraform Deployment

on: 
  workflow_call:
    inputs: 
      environment:
        description: The Azure Environment for deployment 
        required: true
        type: string 



jobs:
  terraform:
    name: Deploy
    runs-on: ubuntu-latest
    #container:
    #  image: hashicorp/terraform:latest
    env:
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.TERRAFORM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.TERRAFORM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.TERRAFORM_SUBSCRIPTION_ID }}
      ARM_ACCESS_KEY: ${{ secrets.TERRAFORM_ACCESS_KEY }}
    defaults:
      run:
        working-directory: ./terraform

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Validate
      if: github.ref == 'refs/heads/main'
      run: |
        terraform init -backend-config="./backend/${{ inputs.environment }}-backend.hcl"
        terraform validate
      env:
        TF_VAR_serviceprinciple_key: ${{ secrets.TERRAFORM_CLIENT_SECRET }}
        TF_VAR_environment: ${{ github.event.inputs.environment }}
        TF_VAR_subscription_id: ${{ secrets.TERRAFORM_SUBSCRIPTION_ID }}

    - name: Terraform Plan
      run: |
        terraform init -backend-config="./backend/${{ github.event.inputs.environment }}-backend.hcl"
        terraform plan -var-file="config/common.tfvars" -var-file="config/${{ github.event.inputs.environment }}.tfvars"
      env:
        TF_VAR_environment: ${{ github.event.inputs.environment }}
        TF_VAR_subscription_id: ${{ secrets.TERRAFORM_SUBSCRIPTION_ID }}

    - name: Terraform Apply
      if: ${{ github.event.inputs.runApply == 'true' }}
      run: |
        terraform init -backend-config="./backend/${{ github.event.inputs.environment }}-backend.hcl"
        terraform apply -var-file="config/common.tfvars" -var-file="config/${{ github.event.inputs.environment }}.tfvars" -auto-approve -input=false
      env:
        TF_VAR_environment: ${{ github.event.inputs.environment }}
        TF_VAR_subscription_id: ${{ secrets.TERRAFORM_SUBSCRIPTION_ID }}